name: Run Newman Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman Collection
        run: newman run "Weather API Tests - Day 9.postman_collection.json" -e "Weather API Testing.postman_environment.json" -r json --reporter-json-export Day9Results.json
