name: Run Newman Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman Collection
        run: newman run WeatherAPITests_Day9postman_collection.json -e WeatherAPITesting_postman_environment.json --reporters cli,json --reporter-json-export Day9Report.json
      - name: Publish report
        uses: actions/upload-artifact@v3
        with:
          file_path: 'C:/Users/ShruthiShetty/newman-testing/'
          file_name: 'Day9Report.json'
          file_type: 'json'
